version: "3"
services:
  database:
    image: postgres:14
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "postgres" ]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      APP_DB_USER: $DB_USER
      APP_DB_PASS: $DB_PASS
      APP_DB_NAME: $DB_NAME
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"
  app:
    restart: always
    build: .
    command: npm run dev
    volumes:
      - .:/app/
      - /app/node_modules
    environment:
      HOST: $HOST
      PORT: $PORT
      SERVER_LOG: $SERVER_LOG
      DB_HOST: database
      DB_PORT: $DB_PORT
      DB_USER: $DB_USER
      DB_PASS: $DB_PASS
      DB_NAME: $DB_NAME
      DB_SYNC: $DB_SYNC
      DB_LOG: $DB_LOG
      JWT_SECRET: br1g8t3y3s
      HOST_IMAGES: "http://localhost:8080/public/images/"
    depends_on: 
      - database
    links:
      - database
    ports:
      - "8080:8080"
