version: "3"
services:
  database:
    image: postgres:14
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "postgres" ]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      APP_DB_USER: postgres
      APP_DB_PASS: root
      APP_DB_NAME: brighteyes
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"
  app:
    restart: always
    build: .
    command: npm run dev
    volumes:
      - .:/app/
      - /app/node_modules
    environment:
      HOST: '0.0.0.0'
      PORT: 8080
      SERVER_LOG: false
      DB_HOST: database
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASS: root
      DB_NAME: brighteyes
      DB_SYNC: false
      DB_LOG: false
      JWT_SECRET: br1g8t3y3s
      HOST_IMAGES: "http://localhost:8080/public/images/"
    depends_on: 
      - database
    links:
      - database
    ports:
      - "8080:8080"
