version: "3"
services:
  app:
    restart: always
    build: .
    depends_on:
      - postgres
    links:
      - postgres
    environment:
      PORT: 8080
      SERVER_LOG: false
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: root
      DB_PASS: root
      DB_NAME: brighteyes
      DB_SYNC: true
      DB_LOG: false
      JWT_SECRET: br1g8t3y3s
    ports:
      - "8080:8080"
    command: npm run dev
    volumes:
      - .:/app/
      - /app/node_modules

  postgres:
    image: postgres:14
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "postgres" ]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      APP_DB_USER: root
      APP_DB_PASS: root
      APP_DB_NAME: brighteyes
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"
