version: "3"
services:
  app:
    restart: on-failure
    build: .
    depends_on:
      - postgres
    environment:
      PORT: 8080
      SERVER_LOG: false
      DB_HOST: localhost
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASS: root
      DB_NAME: brighteyes
      DB_SYNC: true
      DB_LOG: false
      JWT_SECRET: br1g8t3y3s
    ports:
      - "8080:8080"
    command: npm run dev
    volumes:
      - .:/app/
      - /app/node_modules

  postgres:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: brighteyes
